### ISSUE TITLE
Add configuration for mission designers

### ISSUE THREAD

**Issue by DasCleverle** [Serious-Uglies/LiveMap#4]
We should provide mission designers with a possibility to configure the export. In the first run we should include these options:
* `TcpExport.coalitions`: Set's the coalitions to be exported
* `TcpExport.interval`: For unit heavy missions, it might be a good idea to overwrite the export interval defined in config.lua
* `TcpExport.exportUnits`: Set to true to export units (default: true)
* `TcpExport.exportStatics`: Set to true to export static objects (default: true)
* `TcpExport.exportAirbases`: Set to true to export airbases (default: true)

**Comment by UglySkyfire** [comment]
Might be necessary to handle units and statics differently for the coalitions. Red ones might be invisible and follow the "fog of war" principle for general units. So they only appear if recon found them.
